### ISSUE TITLE
minor typos

### ISSUE THREAD

**Issue by david-lippert** [engineersCode/facultydev1#1]
Hi Lorena,

This looks great!  I found a couple of minor typos that I fixed, but I don't think I have access as a contributor.  I'm happy to push my typo branch if you want to give me permission, or if you don't then I completely understand.  I'm still a rookie at using github (though I use gitlab for my job) so let me know how best to proceed.  Thanks!  This is David Lippert FYI.

**Comment by kyleniemeyer** [comment]
@kcdoo hi David- can you submit these changes as a pull request?

**Comment by david-lippert** [comment]
Do I need to fork the project to do this?

**Comment by labarba** [comment]
👋 @kcdoo – thanks. If you want to submit changes for review, we'll need it via a pull request, as it isn't good form for collaborators to push directly to master.

**Comment by labarba** [comment]
But I looked at the diff on your [commit](https://github.com/kcdoo/facultydev1/commit/ac17cecc69e7813c3eb477838dedc648d446dfc5) and made the changes manually, in this case.
